// <auto-generated />
using System;
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lingarr.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    [Migration("20260318170434_AddTranslationRequestIndexes")]
    partial class AddTranslationRequestIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lingarr.Core.Entities.ApiUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_api_usage_logs");

                    b.HasIndex("Service")
                        .HasDatabaseName("ix_api_usage_logs_service");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_api_usage_logs_timestamp");

                    b.ToTable("api_usage_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.DailyStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("TranslationCount")
                        .HasColumnType("integer")
                        .HasColumnName("translation_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_statistics");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ux_daily_statistics_date");

                    b.ToTable("daily_statistics", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.EmbeddedSubtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodecName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codec_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<string>("ExtractedPath")
                        .HasColumnType("text")
                        .HasColumnName("extracted_path");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsExtracted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extracted");

                    b.Property<bool>("IsForced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forced");

                    b.Property<bool>("IsTextBased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_text_based");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("integer")
                        .HasColumnName("stream_index");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_embedded_subtitles");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_embedded_subtitles_episode_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_embedded_subtitles_movie_id");

                    b.ToTable("embedded_subtitles", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<DateTime?>("LastSubtitleCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_subtitle_check_at");

                    b.Property<string>("MediaHash")
                        .HasColumnType("text")
                        .HasColumnName("media_hash");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<int>("SonarrId")
                        .HasColumnType("integer")
                        .HasColumnName("sonarr_id");

                    b.Property<string>("SourceInstanceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_instance_id");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("state_settings_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TranslationState")
                        .HasColumnType("integer")
                        .HasColumnName("translation_state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_episodes_season_id");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_Episodes_TranslationState");

                    b.HasIndex("SourceInstanceId", "SonarrId")
                        .IsUnique()
                        .HasDatabaseName("IX_Episodes_SourceInstanceId_SonarrId");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_error_logs");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_error_logs_timestamp");

                    b.ToTable("error_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int?>("ShowId")
                        .HasColumnType("integer")
                        .HasColumnName("show_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_images_movie_id");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("ix_images_show_id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean")
                        .HasColumnName("is_priority");

                    b.Property<DateTime?>("LastSubtitleCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_subtitle_check_at");

                    b.Property<string>("MediaHash")
                        .HasColumnType("text")
                        .HasColumnName("media_hash");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime?>("PriorityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("priority_date");

                    b.Property<int>("RadarrId")
                        .HasColumnType("integer")
                        .HasColumnName("radarr_id");

                    b.Property<string>("SourceInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("source_instance_id");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("state_settings_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TranslationAgeThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("translation_age_threshold");

                    b.Property<int>("TranslationState")
                        .HasColumnType("integer")
                        .HasColumnName("translation_state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_Movies_TranslationState");

                    b.HasIndex("SourceInstanceId", "RadarrId")
                        .IsUnique()
                        .HasDatabaseName("IX_Movies_SourceInstanceId_RadarrId");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.PathMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_path");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_path_mappings");

                    b.ToTable("path_mappings", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer")
                        .HasColumnName("show_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("ix_seasons_show_id");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_added");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude_from_translation");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean")
                        .HasColumnName("is_priority");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<DateTime?>("PriorityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("priority_date");

                    b.Property<int>("SonarrId")
                        .HasColumnType("integer")
                        .HasColumnName("sonarr_id");

                    b.Property<string>("SourceInstanceId")
                        .HasColumnType("text")
                        .HasColumnName("source_instance_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TranslationAgeThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("translation_age_threshold");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shows");

                    b.HasIndex("SourceInstanceId", "SonarrId")
                        .IsUnique()
                        .HasDatabaseName("IX_Shows_SourceInstanceId_SonarrId");

                    b.ToTable("shows", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SubtitlesByLanguageJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitles_by_language_json");

                    b.Property<long>("TotalCharactersTranslated")
                        .HasColumnType("bigint")
                        .HasColumnName("total_characters_translated");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("total_episodes");

                    b.Property<long>("TotalFilesTranslated")
                        .HasColumnType("bigint")
                        .HasColumnName("total_files_translated");

                    b.Property<long>("TotalLinesTranslated")
                        .HasColumnType("bigint")
                        .HasColumnName("total_lines_translated");

                    b.Property<int>("TotalMovies")
                        .HasColumnType("integer")
                        .HasColumnName("total_movies");

                    b.Property<int>("TotalSubtitles")
                        .HasColumnType("integer")
                        .HasColumnName("total_subtitles");

                    b.Property<string>("TranslationsByMediaTypeJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translations_by_media_type_json");

                    b.Property<string>("TranslationsByServiceJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translations_by_service_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_statistics");

                    b.ToTable("statistics", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.SubtitleCleanupLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("NewMediaFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_media_file_name");

                    b.Property<string>("OriginalMediaFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_media_file_name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_subtitle_cleanup_logs");

                    b.ToTable("subtitle_cleanup_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiCallsJson")
                        .HasColumnType("text")
                        .HasColumnName("api_calls_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedLines")
                        .HasColumnType("integer")
                        .HasColumnName("failed_lines");

                    b.Property<string>("LineResultsJson")
                        .HasColumnType("text")
                        .HasColumnName("line_results_json");

                    b.Property<string>("PosterPath")
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<string>("PreviewJson")
                        .HasColumnType("text")
                        .HasColumnName("preview_json");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_language");

                    b.Property<string>("SubtitlePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitle_path");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_language");

                    b.Property<string>("TimingJson")
                        .HasColumnType("text")
                        .HasColumnName("timing_json");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TokenUsageCompletion")
                        .HasColumnType("integer")
                        .HasColumnName("token_usage_completion");

                    b.Property<int?>("TokenUsagePrompt")
                        .HasColumnType("integer")
                        .HasColumnName("token_usage_prompt");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer")
                        .HasColumnName("total_lines");

                    b.Property<int>("TranslatedLines")
                        .HasColumnType("integer")
                        .HasColumnName("translated_lines");

                    b.Property<string>("TranslationService")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation_service");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_test_results");

                    b.ToTable("test_results", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TranslationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsForcedSubtitle")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forced_subtitle");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("boolean")
                        .HasColumnName("is_priority");

                    b.Property<string>("JobId")
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<int?>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer")
                        .HasColumnName("media_type");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("SelectedStreamTitle")
                        .HasColumnType("text")
                        .HasColumnName("selected_stream_title");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_language");

                    b.Property<int>("SourceSubtitleEntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_subtitle_entry_count");

                    b.Property<string>("SourceSubtitleType")
                        .HasColumnType("text")
                        .HasColumnName("source_subtitle_type");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SubtitleToTranslate")
                        .HasColumnType("text")
                        .HasColumnName("subtitle_to_translate");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TranslatedSubtitle")
                        .HasColumnType("text")
                        .HasColumnName("translated_subtitle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_translation_requests");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_translation_requests_completed_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_translation_requests_status");

                    b.HasIndex("MediaId", "MediaType", "SourceLanguage", "TargetLanguage", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_translation_requests_active_dedupe");

                    b.ToTable("translation_requests", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TranslationRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("TranslationRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("translation_request_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_translation_request_logs");

                    b.HasIndex("TranslationRequestId")
                        .HasDatabaseName("ix_translation_request_logs_translation_request_id");

                    b.ToTable("translation_request_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.EmbeddedSubtitle", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Episode", "Episode")
                        .WithMany("EmbeddedSubtitles")
                        .HasForeignKey("EpisodeId")
                        .HasConstraintName("fk_embedded_subtitles_episodes_episode_id");

                    b.HasOne("Lingarr.Core.Entities.Movie", "Movie")
                        .WithMany("EmbeddedSubtitles")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("fk_embedded_subtitles_movies_movie_id");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Image", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Movie", "Movie")
                        .WithMany("Images")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_images_movies_movie_id");

                    b.HasOne("Lingarr.Core.Entities.Show", "Show")
                        .WithMany("Images")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_images_shows_show_id");

                    b.Navigation("Movie");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Season", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Show", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_shows_show_id");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TranslationRequestLog", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.TranslationRequest", "TranslationRequest")
                        .WithMany()
                        .HasForeignKey("TranslationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_translation_request_logs_translation_requests_translation_r");

                    b.Navigation("TranslationRequest");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.Navigation("EmbeddedSubtitles");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Movie", b =>
                {
                    b.Navigation("EmbeddedSubtitles");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Show", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
