// <auto-generated />
using System;
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lingarr.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    [Migration("20260210040000_FixEmbeddedSubtitlesColumns")]
    partial class FixEmbeddedSubtitlesColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lingarr.Core.Entities.EmbeddedSubtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodecName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codec_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_id");

                    b.Property<string>("ExtractedPath")
                        .HasColumnType("text")
                        .HasColumnName("extracted_path");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsExtracted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_extracted");

                    b.Property<bool>("IsForced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forced");

                    b.Property<bool>("IsHearingImpaired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hearing_impaired");

                    b.Property<bool>("IsTextBased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_text_based");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_id");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("integer")
                        .HasColumnName("stream_index");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_embedded_subtitles");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("ix_embedded_subtitles_episode_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_embedded_subtitles_movie_id");

                    b.ToTable("embedded_subtitles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
