// <auto-generated />
using System;
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lingarr.Migrations.PostgreSQL.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    [Migration("20260118212500_ResetMissingEmbeddedSubtitleIndex")]
    partial class ResetMissingEmbeddedSubtitleIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a data-only migration, no model changes
            // Copy the model from the previous migration snapshot
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Model is identical to previous migration - this is data-only
            // Referencing LingarrDbContextModelSnapshot for full model
#pragma warning restore 612, 618
        }
    }
}
