// <auto-generated />
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lingarr.Migrations.MySQL.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    [Migration("20251212133000_AddTranslationRequestActiveDedupe")]
    partial class AddTranslationRequestActiveDedupe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}

