// <auto-generated />
using System;
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lingarr.Migrations.SQLite.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    [Migration("20251217010436_AddTranslationStateTracking")]
    partial class AddTranslationStateTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Lingarr.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_Movies_TranslationState");

                    b.ToTable("movies");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_Episodes_TranslationState");

                    b.ToTable("episodes");
                });
#pragma warning restore 612, 618
        }
    }
}
