// <auto-generated />
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lingarr.Migrations.SQLite.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    [Migration("20251212171800_AddSubtitleIntegrityValidation")]
    partial class AddSubtitleIntegrityValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
