// <auto-generated />
using System;
using Lingarr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lingarr.Migrations.SQLite.Migrations
{
    [DbContext(typeof(LingarrDbContext))]
    partial class LingarrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Lingarr.Core.Entities.ApiUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prompt_tokens");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("service");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_api_usage_logs");

                    b.HasIndex("Service")
                        .HasDatabaseName("ix_api_usage_logs_service");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_api_usage_logs_timestamp");

                    b.ToTable("api_usage_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.CustomMediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomSourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("custom_source_id");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_added");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_priority");

                    b.Property<int>("ItemKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_kind");

                    b.Property<DateTime?>("LastSubtitleCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_subtitle_check_at");

                    b.Property<string>("MediaHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_hash");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTime?>("PriorityDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("priority_date");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<string>("SeriesTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("series_title");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_settings_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("TranslationState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_custom_media_items");

                    b.HasIndex("CustomSourceId")
                        .HasDatabaseName("IX_CustomMediaItems_CustomSourceId");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_CustomMediaItems_TranslationState");

                    b.HasIndex("CustomSourceId", "Path")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomMediaItems_CustomSourceId_Path");

                    b.ToTable("custom_media_items", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.CustomSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<bool>("IncludeInAutomation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("include_in_automation");

                    b.Property<string>("LastScanError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scan_error");

                    b.Property<string>("LastScanResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scan_result");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_scanned_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<bool>("Recursive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recursive");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("root_path");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_custom_sources");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CustomSources_Name");

                    b.HasIndex("RootPath")
                        .HasDatabaseName("IX_CustomSources_RootPath");

                    b.ToTable("custom_sources", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.DailyStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<int>("TranslationCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_daily_statistics");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("ux_daily_statistics_date");

                    b.ToTable("daily_statistics", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.EmbeddedSubtitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CodecName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codec_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<string>("ExtractedPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("extracted_path");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsExtracted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_extracted");

                    b.Property<bool>("IsForced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_forced");

                    b.Property<bool>("IsTextBased")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_text_based");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stream_index");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_embedded_subtitles");

                    b.HasIndex("EpisodeId")
                        .HasDatabaseName("IX_EmbeddedSubtitles_EpisodeId");

                    b.HasIndex("IsExtracted")
                        .HasDatabaseName("IX_EmbeddedSubtitles_IsExtracted");

                    b.HasIndex("Language")
                        .HasDatabaseName("IX_EmbeddedSubtitles_Language");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("IX_EmbeddedSubtitles_MovieId");

                    b.HasIndex("EpisodeId", "IsExtracted")
                        .HasDatabaseName("IX_EmbeddedSubtitles_EpisodeId_IsExtracted");

                    b.HasIndex("MovieId", "IsExtracted")
                        .HasDatabaseName("IX_EmbeddedSubtitles_MovieId_IsExtracted");

                    b.ToTable("embedded_subtitles", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_added");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<DateTime?>("LastSubtitleCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_subtitle_check_at");

                    b.Property<string>("MediaHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_hash");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("SeasonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_id");

                    b.Property<int>("SonarrId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sonarr_id");

                    b.Property<string>("SourceInstanceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_instance_id");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_settings_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("TranslationState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_episodes_season_id");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_Episodes_TranslationState");

                    b.HasIndex("SourceInstanceId", "SonarrId")
                        .IsUnique()
                        .HasDatabaseName("IX_Episodes_SourceInstanceId_SonarrId");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_trace");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_error_logs");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_error_logs_timestamp");

                    b.ToTable("error_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int?>("ShowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_images");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_images_movie_id");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("ix_images_show_id");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_added");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("indexed_at");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_priority");

                    b.Property<DateTime?>("LastSubtitleCheckAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_subtitle_check_at");

                    b.Property<string>("MediaHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_hash");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTime?>("PriorityDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("priority_date");

                    b.Property<int>("RadarrId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("radarr_id");

                    b.Property<string>("SourceInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_instance_id");

                    b.Property<int>("StateSettingsVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state_settings_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("TranslationAgeThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_age_threshold");

                    b.Property<int>("TranslationState")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_movies");

                    b.HasIndex("TranslationState")
                        .HasDatabaseName("IX_Movies_TranslationState");

                    b.HasIndex("SourceInstanceId", "RadarrId")
                        .IsUnique()
                        .HasDatabaseName("IX_Movies_SourceInstanceId_RadarrId");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.PathMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("destination_path");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_type");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_path_mappings");

                    b.ToTable("path_mappings", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_translation");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<int>("ShowId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("SeasonNumber")
                        .HasDatabaseName("IX_Seasons_SeasonNumber");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("IX_Seasons_ShowId");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_added");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_translation");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_priority");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<DateTime?>("PriorityDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("priority_date");

                    b.Property<int>("SonarrId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sonarr_id");

                    b.Property<string>("SourceInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_instance_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("TranslationAgeThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_age_threshold");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shows");

                    b.HasIndex("SourceInstanceId", "SonarrId")
                        .IsUnique()
                        .HasDatabaseName("IX_Shows_SourceInstanceId_SonarrId");

                    b.ToTable("shows", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("SubtitlesByLanguageJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitles_by_language_json");

                    b.Property<long>("TotalCharactersTranslated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_characters_translated");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_episodes");

                    b.Property<long>("TotalFilesTranslated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_files_translated");

                    b.Property<long>("TotalLinesTranslated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_lines_translated");

                    b.Property<int>("TotalMovies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_movies");

                    b.Property<int>("TotalSubtitles")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_subtitles");

                    b.Property<string>("TranslationsByMediaTypeJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_by_media_type_json");

                    b.Property<string>("TranslationsByServiceJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("translations_by_service_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_statistics");

                    b.ToTable("statistics", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.SubtitleCleanupLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("NewMediaFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("new_media_file_name");

                    b.Property<string>("OriginalMediaFileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("original_media_file_name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_subtitle_cleanup_logs");

                    b.ToTable("subtitle_cleanup_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ApiCallsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("api_calls_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("failed_lines");

                    b.Property<string>("LineResultsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("line_results_json");

                    b.Property<string>("PosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("poster_path");

                    b.Property<string>("PreviewJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("preview_json");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_language");

                    b.Property<string>("SubtitlePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitle_path");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_language");

                    b.Property<string>("TimingJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("timing_json");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("TokenUsageCompletion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_usage_completion");

                    b.Property<int?>("TokenUsagePrompt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("token_usage_prompt");

                    b.Property<int>("TotalLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_lines");

                    b.Property<int>("TranslatedLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translated_lines");

                    b.Property<string>("TranslationService")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("translation_service");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_test_results");

                    b.ToTable("test_results", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TranslationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomMediaItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("custom_media_item_id");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_at");

                    b.Property<string>("GeneratedOutputFormats")
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_output_formats");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsForcedSubtitle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_forced_subtitle");

                    b.Property<bool>("IsPriority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_priority");

                    b.Property<string>("JobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<int?>("MediaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_id");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("media_type");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<string>("RequiredOutputFormats")
                        .HasColumnType("TEXT")
                        .HasColumnName("required_output_formats");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<string>("SelectedStreamTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_stream_title");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_language");

                    b.Property<long?>("SourceSnapshotFileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_snapshot_file_size_bytes");

                    b.Property<string>("SourceSnapshotFingerprint")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_snapshot_fingerprint");

                    b.Property<string>("SourceSnapshotIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_snapshot_identity");

                    b.Property<DateTime?>("SourceSnapshotLastWriteUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_snapshot_last_write_utc");

                    b.Property<int?>("SourceSnapshotStreamIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_snapshot_stream_index");

                    b.Property<string>("SourceSnapshotType")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_snapshot_type");

                    b.Property<int>("SourceSnapshotVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("source_snapshot_version");

                    b.Property<int>("SourceSubtitleEntryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_subtitle_entry_count");

                    b.Property<string>("SourceSubtitleFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_subtitle_format");

                    b.Property<string>("SourceSubtitleType")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_subtitle_type");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("SubtitleOutputMode")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitle_output_mode");

                    b.Property<string>("SubtitleToTranslate")
                        .HasColumnType("TEXT")
                        .HasColumnName("subtitle_to_translate");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_language");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("TranslatedSubtitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("translated_subtitle");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UploadBatchFileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upload_batch_file_id");

                    b.Property<string>("WorkloadItemKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("workload_item_key");

                    b.Property<int>("WorkloadKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("workload_kind");

                    b.HasKey("Id")
                        .HasName("pk_translation_requests");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_translation_requests_completed_at");

                    b.HasIndex("FailedAt")
                        .HasDatabaseName("IX_TranslationRequests_FailedAt");

                    b.HasIndex("IsPriority")
                        .HasDatabaseName("IX_TranslationRequests_IsPriority");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("IX_TranslationRequests_NextRetryAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_TranslationRequests_Status");

                    b.HasIndex("Status", "IsPriority", "CreatedAt")
                        .HasDatabaseName("IX_TranslationRequests_Status_Priority_Created");

                    b.HasIndex("WorkloadItemKey", "SourceLanguage", "TargetLanguage", "RequiredOutputFormats", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_translation_requests_active_dedupe");

                    b.HasIndex("WorkloadItemKey", "TargetLanguage", "RequiredOutputFormats", "Status", "CompletedAt")
                        .HasDatabaseName("IX_TranslationRequests_FreshnessLookup");

                    b.ToTable("translation_requests", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TranslationRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int>("TranslationRequestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("translation_request_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_translation_request_logs");

                    b.HasIndex("Level")
                        .HasDatabaseName("IX_TranslationRequestLog_Level");

                    b.HasIndex("TranslationRequestId")
                        .HasDatabaseName("IX_TranslationRequestLog_TranslationRequestId");

                    b.ToTable("translation_request_logs", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadArtifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_downloadable");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UploadBatchFileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upload_batch_file_id");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upload_batch_id");

                    b.HasKey("Id")
                        .HasName("pk_upload_artifacts");

                    b.HasIndex("UploadBatchFileId")
                        .HasDatabaseName("IX_UploadArtifacts_UploadBatchFileId");

                    b.HasIndex("UploadBatchId")
                        .HasDatabaseName("IX_UploadArtifacts_UploadBatchId");

                    b.HasIndex("UploadBatchFileId", "Kind")
                        .HasDatabaseName("IX_UploadArtifacts_UploadBatchFileId_Kind");

                    b.ToTable("upload_artifacts", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("DefaultRemuxEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("default_remux_enabled");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_language");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_upload_batches");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UploadBatches_ExpiresAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_UploadBatches_Status");

                    b.ToTable("upload_batches", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatchFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentTranslationRequestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_translation_request_id");

                    b.Property<string>("DetectedSourceLanguage")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("detected_source_language");

                    b.Property<bool>("EmbedTranslatedSubtitle")
                        .HasColumnType("INTEGER")
                        .HasColumnName("embed_translated_subtitle");

                    b.Property<bool>("ExcludeFromTranslation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_translation");

                    b.Property<int>("FileKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_kind");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("LastError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT")
                        .HasColumnName("original_file_name");

                    b.Property<DateTime?>("ProbeCompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("probe_completed_at");

                    b.Property<string>("ProbeError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("probe_error");

                    b.Property<string>("RelativeStoredPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_stored_path");

                    b.Property<string>("SelectedEmbeddedStreamCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_embedded_stream_codec");

                    b.Property<int?>("SelectedEmbeddedStreamIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("selected_embedded_stream_index");

                    b.Property<string>("SelectedEmbeddedStreamLanguage")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_embedded_stream_language");

                    b.Property<string>("SelectedEmbeddedStreamTitle")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_embedded_stream_title");

                    b.Property<string>("SelectedSourceLanguage")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("selected_source_language");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("stored_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadBatchId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upload_batch_id");

                    b.HasKey("Id")
                        .HasName("pk_upload_batch_files");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_UploadBatchFiles_Status");

                    b.HasIndex("UploadBatchId")
                        .HasDatabaseName("IX_UploadBatchFiles_UploadBatchId");

                    b.HasIndex("UploadBatchId", "OriginalFileName")
                        .HasDatabaseName("IX_UploadBatchFiles_UploadBatchId_OriginalFileName");

                    b.ToTable("upload_batch_files", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatchFileSubtitleStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CodecName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("codec_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsForced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_forced");

                    b.Property<bool>("IsTextBased")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_text_based");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stream_index");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UploadBatchFileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upload_batch_file_id");

                    b.HasKey("Id")
                        .HasName("pk_upload_batch_file_subtitle_streams");

                    b.HasIndex("UploadBatchFileId")
                        .HasDatabaseName("IX_UploadBatchFileSubtitleStreams_UploadBatchFileId");

                    b.HasIndex("UploadBatchFileId", "StreamIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_UploadBatchFileSubtitleStreams_UploadBatchFileId_StreamIndex");

                    b.ToTable("upload_batch_file_subtitle_streams", (string)null);
                });

            modelBuilder.Entity("Lingarr.Core.Entities.CustomMediaItem", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.CustomSource", "CustomSource")
                        .WithMany("Items")
                        .HasForeignKey("CustomSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_media_items_custom_sources_custom_source_id");

                    b.Navigation("CustomSource");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.EmbeddedSubtitle", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Episode", "Episode")
                        .WithMany("EmbeddedSubtitles")
                        .HasForeignKey("EpisodeId")
                        .HasConstraintName("fk_embedded_subtitles_episodes_episode_id");

                    b.HasOne("Lingarr.Core.Entities.Movie", "Movie")
                        .WithMany("EmbeddedSubtitles")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("fk_embedded_subtitles_movies_movie_id");

                    b.Navigation("Episode");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_seasons_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Image", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Movie", "Movie")
                        .WithMany("Images")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_images_movies_movie_id");

                    b.HasOne("Lingarr.Core.Entities.Show", "Show")
                        .WithMany("Images")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_images_shows_show_id");

                    b.Navigation("Movie");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Season", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.Show", "Show")
                        .WithMany("Seasons")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_shows_show_id");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.TranslationRequestLog", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.TranslationRequest", "TranslationRequest")
                        .WithMany()
                        .HasForeignKey("TranslationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_translation_request_logs_translation_requests_translation_request_id");

                    b.Navigation("TranslationRequest");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadArtifact", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.UploadBatchFile", "UploadBatchFile")
                        .WithMany("Artifacts")
                        .HasForeignKey("UploadBatchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_upload_artifacts_upload_batch_files_upload_batch_file_id");

                    b.HasOne("Lingarr.Core.Entities.UploadBatch", "UploadBatch")
                        .WithMany("Artifacts")
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_upload_artifacts_upload_batches_upload_batch_id");

                    b.Navigation("UploadBatch");

                    b.Navigation("UploadBatchFile");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatchFile", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.UploadBatch", "UploadBatch")
                        .WithMany("Files")
                        .HasForeignKey("UploadBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_upload_batch_files_upload_batches_upload_batch_id");

                    b.Navigation("UploadBatch");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatchFileSubtitleStream", b =>
                {
                    b.HasOne("Lingarr.Core.Entities.UploadBatchFile", "UploadBatchFile")
                        .WithMany("SubtitleStreams")
                        .HasForeignKey("UploadBatchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_upload_batch_file_subtitle_streams_upload_batch_files_upload_batch_file_id");

                    b.Navigation("UploadBatchFile");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.CustomSource", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Episode", b =>
                {
                    b.Navigation("EmbeddedSubtitles");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Movie", b =>
                {
                    b.Navigation("EmbeddedSubtitles");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.Show", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatch", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Lingarr.Core.Entities.UploadBatchFile", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("SubtitleStreams");
                });
#pragma warning restore 612, 618
        }
    }
}
